// SALMOS · Directorio de clientes y ofertas por WhatsApp.
(() => {
  'use strict';
  let ctx,items=[],selected=new Set(),filters={},offerFiles=[];
  const $=s=>document.querySelector(s),esc=v=>ctx.escapeHtml(String(v??''));
  const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es');
  const fields=[['name','Nombre'],['phone','Teléfono'],['email','Mail'],['address','Dirección'],['locality','Localidad'],['province','Provincia'],['zone','Zona'],['usual_shipping','Envío habitual']];
  function dialog(id,title){let el=$('#'+id);if(!el){el=document.createElement('dialog');el.className='admin-dialog client-dialog';el.id=id;document.body.append(el);}el.innerHTML=`<div class="dialog-shell"><div class="dialog-head"><h2>${esc(title)}</h2><button type="button" class="icon-btn" data-client-close aria-label="Cerrar">×</button></div><div class="dialog-body"></div></div>`;el.querySelector('[data-client-close]').onclick=()=>el.close();return el;}
  async function load(){items=(await ctx.api('/api/admin/clients')).items||[];items.sort((a,b)=>a.name.localeCompare(b.name,'es',{sensitivity:'base'}));selected=new Set([...selected].filter(id=>items.some(c=>c.id===id)));}
  function visible(){return items.filter(c=>['search','locality','province','zone'].every(key=>!filters[key]||norm(key==='search'?[c.name,c.phone,c.email].join(' '):c[key]).includes(norm(filters[key]))));}
  function rows(){const host=$('#clientDirectoryRows');if(!host)return;host.innerHTML=visible().map(c=>`<article class="client-row"><label class="client-select"><input type="checkbox" data-client-select="${c.id}" ${selected.has(c.id)?'checked':''} aria-label="Marcar ${esc(c.name)}"></label><button class="client-open" type="button" data-client-edit="${c.id}"><strong>${esc(c.name)}</strong><span>${esc(c.phone)}${c.email?' · '+esc(c.email):''}</span><span>${esc([c.address,c.locality,c.province,c.zone].filter(Boolean).join(' · '))}</span><span>${esc(c.usual_shipping)} · ${ctx.money(c.last_shipping_cost_cents)} · ${(c.orders||[]).length} pedidos</span></button></article>`).join('')||'<p class="muted">Sin clientes en este filtro.</p>';const btn=$('[data-client-select-all]');if(btn)btn.textContent=visible().length&&visible().every(c=>selected.has(c.id))?'Desmarcar todos':'Marcar todos';const offer=$('[data-client-offer]');if(offer)offer.disabled=!selected.size;}
  async function render(){await load();$('#adminContent').innerHTML=`<div class="admin-section-head"><h2>Clientes</h2><div class="admin-actions"><button type="button" class="btn btn-ghost" data-client-select-all>Marcar todos</button><button type="button" class="btn btn-primary" data-client-new>+ Cliente</button><button type="button" class="btn btn-ghost" data-client-import><i class="fa-solid fa-address-book" aria-hidden="true"></i> Importar contactos</button><button type="button" class="btn btn-primary" data-client-offer>Oferta por WhatsApp</button></div></div><div class="client-filters">${[['search','Buscar nombre / teléfono'],['locality','Localidad'],['province','Provincia'],['zone','Zona']].map(([key,label])=>`<label class="field">${label}<input class="input" data-client-filter="${key}" value="${esc(filters[key]||'')}" type="search"></label>`).join('')}</div><section id="clientDirectoryRows"></section>`;rows();}
  async function edit(client=null,onSave=null){const el=dialog('clientEditDialog',client?'Editar cliente':'Agregar cliente'),body=el.querySelector('.dialog-body');body.innerHTML=`<form id="clientEditForm"><div class="form-grid">${fields.map(([key,label])=>`<label class="field">${label}<input class="input" name="${key}" value="${esc(client?.[key])}" ${key==='name'?'required maxlength="160"':'maxlength="500"'} type="${key==='email'?'email':key==='phone'?'tel':'text'}" ${key==='phone'?'placeholder="+54 9 …"':''}></label>`).join('')}<label class="field">Último costo de envío ($)<input class="input" name="shippingCost" type="number" min="0" step=".01" value="${(client?.last_shipping_cost_cents||0)/100}"></label></div>${client?.orders?.length?`<section class="client-orders"><h3>Pedidos</h3>${client.orders.map(o=>`<div><strong>${esc(o.code||'#'+o.id)}</strong><span>${esc(o.status)} · ${ctx.money(o.total_cents)}</span><button type="button" class="btn btn-ghost" data-client-order="${o.kind}">Ver ${o.kind==='custom'?'pedidos':'órdenes'}</button></div>`).join('')}</section>`:''}<div class="admin-actions"><button type="submit" class="btn btn-primary">Guardar</button>${client?'<button type="button" class="icon-btn" data-client-delete aria-label="Eliminar cliente"><i class="fa-solid fa-trash-can" aria-hidden="true"></i></button>':''}</div><p role="status" class="client-form-status"></p></form>`;
    const form=body.querySelector('form');form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;try{const data=Object.fromEntries(new FormData(form));data.last_shipping_cost_cents=Math.round(Number(data.shippingCost)*100);if(client)data.revision=client.revision;const result=await ctx.api('/api/admin/clients'+(client?'/'+client.id:''),{method:client?'PATCH':'POST',body:JSON.stringify(data)});if(onSave)await onSave(result.item);el.close();if($('#clientDirectoryRows'))await render();ctx.toast('Cliente guardado','success');}catch(err){form.querySelector('[role=status]').textContent=err.message;}finally{button.disabled=false;}};
    if(client)body.querySelector('[data-client-delete]').onclick=async()=>{if(!confirm('¿Eliminar este cliente del directorio?'))return;try{await ctx.api('/api/admin/clients/'+client.id,{method:'DELETE',body:JSON.stringify({revision:client.revision})});selected.delete(client.id);el.close();await render();}catch(err){ctx.toast(err.message,'error');}};
    el.showModal();form.elements.name.focus();
  }
  async function choose(onChoose){await load();const el=dialog('clientChooseDialog','Elegir cliente');el.querySelector('.dialog-body').innerHTML=`<label class="field">Buscar<input class="input" data-client-pick-search type="search"></label><div class="client-pick-list"></div>`;const draw=query=>{el.querySelector('.client-pick-list').innerHTML=items.filter(c=>norm(c.name+' '+c.phone).includes(norm(query))).map(c=>`<button type="button" class="btn btn-ghost" data-client-pick="${c.id}">${esc(c.name)} · ${esc(c.phone)}</button>`).join('');};draw('');el.querySelector('input').oninput=e=>draw(e.target.value);el.addEventListener('click',e=>{const b=e.target.closest('[data-client-pick]');if(b){onChoose(items.find(c=>c.id===Number(b.dataset.clientPick)));el.close();}},{signal:(el._chooseController?.abort(),(el._chooseController=new AbortController()).signal)});el.showModal();}
  async function offer(){const recipients=items.filter(c=>selected.has(c.id));if(!recipients.length)return;const flyers=(await ctx.api('/api/admin/flyers')).items||[],el=dialog('clientOfferDialog','Oferta por WhatsApp');offerFiles=[];
    const mobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);
    el.querySelector('.dialog-body').innerHTML=`<label class="field">Texto<textarea class="input" id="clientOfferText" rows="3"></textarea></label><details open><summary>Flyers</summary><div class="client-offer-flyers">${flyers.map(f=>`<label><input type="checkbox" data-offer-flyer="${f.id}">${f.mime_type.startsWith('video/')?`<video src="${esc(f.url)}" preload="metadata" muted></video>`:`<img src="${esc(f.url)}" alt="${esc(f.title||'Flyer')}" loading="lazy">`}<span>${esc(f.title||'Flyer')}</span></label>`).join('')||'<p>Sin flyers cargados.</p>'}</div></details><div class="admin-actions"><button type="button" class="btn btn-ghost" data-offer-load>Preparar archivos</button><button type="button" class="btn btn-ghost" data-offer-copy-image disabled>Copiar imagen</button></div><p class="client-offer-status" role="status"></p><div class="client-offer-recipients">${recipients.map(c=>`<div><strong>${esc(c.name)}</strong><button type="button" class="btn btn-primary" data-offer-whatsapp="${c.id}" ${c.phone?'':'disabled'}>${mobile?'WhatsApp':'WhatsApp Web'}</button><button type="button" class="btn btn-ghost" data-offer-share="${c.id}" disabled>Compartir archivo</button><label><input type="checkbox"> Enviado</label></div>`).join('')}</div>`;
    const status=el.querySelector('[role=status]'),chosen=()=>flyers.filter(f=>el.querySelector(`[data-offer-flyer="${f.id}"]`)?.checked);let fileSelection='',preparing=null,clipboardImage=null,generation=0;
    
    const png=async file=>{if(file.type==='image/png')return file;if(!file.type.startsWith('image/'))return null;const url=URL.createObjectURL(file);try{const image=new Image();image.src=url;await image.decode();const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);return await new Promise(resolve=>canvas.toBlob(resolve,'image/png'));}finally{URL.revokeObjectURL(url);}};
    const prepare=async()=>{const picked=chosen(),signature=picked.map(f=>f.id).join(','),turn=++generation;offerFiles=[];clipboardImage=null;el.querySelectorAll('[data-offer-share],[data-offer-whatsapp]').forEach(b=>b.disabled=true);status.textContent=picked.length?'Cargando archivos…':'';
      try{const files=await Promise.all(picked.map(async f=>{const response=await fetch(f.url,{credentials:'include'});if(!response.ok||String(response.headers.get('Content-Type')||'').includes('text/html'))throw new Error('No se pudo cargar el flyer. Revisá la sesión.');const blob=await response.blob(),type=blob.type||f.mime_type;if(!/^(image|video)\//.test(type))throw new Error('El flyer no contiene una imagen o video válido.');const ext=type.startsWith('video/')?'mp4':type.includes('png')?'png':type.includes('webp')?'webp':'jpg',name=f.file_name||'flyer-'+f.id+'.'+ext;return new File([blob],/\.[a-z0-9]+$/i.test(name)?name:name+'.'+ext,{type});}));const clip=files.length===1?await png(files[0]).catch(()=>null):null;if(turn!==generation)return;offerFiles=files;clipboardImage=clip;fileSelection=signature;status.textContent=files.length?'Archivos listos.':'';
      }catch(err){if(turn===generation){status.textContent=err.message;fileSelection='';}}finally{if(turn===generation){const ready=!picked.length||offerFiles.length===picked.length;el.querySelectorAll('[data-offer-whatsapp]').forEach(b=>b.disabled=!ready||!recipients.find(c=>c.id===Number(b.dataset.offerWhatsapp))?.phone);el.querySelectorAll('[data-offer-share]').forEach(b=>b.disabled=!offerFiles.length||!navigator.canShare?.({files:offerFiles}));el.querySelector('[data-offer-copy-image]').disabled=!clipboardImage||!navigator.clipboard?.write||!window.ClipboardItem;}}
    };
    el.querySelector('[data-offer-load]').onclick=()=>{preparing=prepare();};el.querySelector('[data-offer-copy-image]').onclick=async()=>{try{await navigator.clipboard.write([new ClipboardItem({'image/png':clipboardImage})]);status.textContent='Imagen copiada. Abrí el chat y pegala con Ctrl+V.';}catch{status.textContent='El navegador no permitió copiar la imagen. Compartí el archivo desde el teléfono o adjuntalo en WhatsApp.';}};
    el.onchange=e=>{if(e.target.matches('[data-offer-flyer]'))preparing=prepare();};
    el.onclick=async e=>{const share=e.target.closest('[data-offer-share]'),wa=e.target.closest('[data-offer-whatsapp]');if(!share&&!wa)return;const text=$('#clientOfferText').value.trim().replace(/https?:\/\/(?:www\.)?salmos\.com\.ar\/?(?=$|[\s,;!])/gi,'https://salmos.com.ar/compartir.html'),picked=chosen();if(!text&&!picked.length){status.textContent='Agregá texto o un flyer.';return;}if(picked.length&&(offerFiles.length!==picked.length||fileSelection!==picked.map(f=>f.id).join(','))){status.textContent='Esperá a que terminen de cargar los archivos.';return;}
      try{if(share&&offerFiles.length&&navigator.canShare?.({files:offerFiles})&&navigator.share){await navigator.share({files:offerFiles,text});status.textContent='Elegí WhatsApp y el destinatario para completar el envío.';return;}if(share){status.textContent='Este navegador no permite compartir archivos. Usá WhatsApp o descargalos.';return;}
        const c=recipients.find(c=>c.id===Number(wa.dataset.offerWhatsapp)),phone=c.phone.replace(/\D/g,'').replace(/^00/,'');if(phone.length<7){status.textContent='Completá el teléfono con código de país.';return;}
        const link=(mobile?'https://wa.me/'+phone+'?text=':'https://web.whatsapp.com/send?phone='+phone+'&text=')+encodeURIComponent(text),popup=window.open(link,'_blank');if(popup)popup.opener=null;
        if(!popup){status.textContent='Permití abrir ventanas y volvé a tocar WhatsApp.';return;}
        status.textContent=offerFiles.length?(clipboardImage?'Chat abierto. Usá Copiar imagen y pegala en WhatsApp.':'Chat abierto. Para el archivo, usá Compartir archivo en el teléfono o adjuntalo en WhatsApp.'):'Confirmá el envío dentro de WhatsApp.';

      }catch(err){if(err.name!=='AbortError')status.textContent='No se pudo compartir: '+err.message;}
    };
    el.showModal();
  }
  async function importContacts(){
    await load();const el=dialog('clientImportDialog','Importar contactos');let contacts=[],marked=new Set(),limit=200,busy=false;const phoneKey=v=>String(v||'').replace(/\D/g,'').replace(/^00/,'');
    const known=new Set(items.map(c=>phoneKey(c.phone)).filter(Boolean));
    el.querySelector('.dialog-body').innerHTML=`<details class="contact-import-guide"><summary>Cómo descargar los contactos</summary><p>Si el contacto está guardado solo en WhatsApp, abrilo, elegí editar y activá «Sincronizar contacto con el teléfono» antes de exportar.</p><p><strong>PC con Google:</strong> abrí <a href="https://contacts.google.com" target="_blank" rel="noopener">Contactos de Google</a>, marcá los contactos y elegí Más acciones → Exportar → CSV de Google.</p><p><strong>Android:</strong> Contactos → Corregir y gestionar → Exportar a archivo → .vcf.</p><p><strong>iPhone:</strong> en <a href="https://www.icloud.com/contacts" target="_blank" rel="noopener">iCloud Contactos</a> seleccioná los contactos → Compartir → Exportar vCard.</p></details><label class="field">Archivo de contactos<input class="input" type="file" accept=".csv,.vcf,text/csv,text/vcard" data-import-file></label><p class="muted">Revisá que los teléfonos incluyan el código de país, por ejemplo +54 9 … para un celular argentino.</p><div class="admin-actions"><button type="button" class="btn btn-ghost" data-import-all disabled>Marcar todos</button><button type="button" class="btn btn-primary" data-import-save disabled>Importar</button></div><p role="status" data-import-status></p><div class="contact-import-preview"></div><button type="button" class="btn btn-ghost" data-import-more hidden>Ver más</button>`;
    const status=el.querySelector('[data-import-status]'),valid=c=>!!String(c.name||'').trim()&&String(c.name).length<=160&&/^[1-9]\d{6,14}$/.test(phoneKey(c.phone));
    const summarize=()=>{let duplicates=0,invalid=0;const seen=new Set(known);contacts.forEach((c,i)=>{if(!valid(c)){invalid++;marked.delete(i);}else if(seen.has(phoneKey(c.phone))){duplicates++;marked.delete(i);}seen.add(phoneKey(c.phone));});status.textContent=contacts.length+' contactos · '+marked.size+' marcados · '+duplicates+' repetidos · '+invalid+' para revisar';el.querySelector('[data-import-save]').disabled=busy||!marked.size;el.querySelector('[data-import-all]').disabled=busy||!contacts.length;el.querySelector('[data-import-save]').textContent='Importar '+marked.size;};
    const draw=()=>{el.querySelector('.contact-import-preview').innerHTML=contacts.slice(0,limit).map((c,i)=>`<div class="contact-import-row" data-import-row="${i}"><input type="checkbox" data-import-select="${i}" ${marked.has(i)?'checked':''} aria-label="Importar ${esc(c.name)}"><input class="input" data-import-name="${i}" value="${esc(c.name)}" aria-label="Nombre del contacto"><input class="input" data-import-phone="${i}" value="${esc(c.phone)}" aria-label="Teléfono con código de país"><span>${known.has(phoneKey(c.phone))?'Ya existe':valid(c)?'Listo':'Revisar nombre / teléfono'}</span></div>`).join('');el.querySelector('[data-import-more]').hidden=contacts.length<=limit;summarize();};
    el.querySelector('[data-import-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024){contacts=[];marked.clear();draw();status.textContent='El archivo supera 10 MB.';return;}try{contacts=window.SalmosContacts.parse(await file.text(),file.name).map(c=>({...c,name:c.name||c.phone}));marked=new Set(contacts.map((_,i)=>i));limit=200;draw();}catch(error){contacts=[];marked.clear();draw();status.textContent=error.message;}};
    el.querySelector('[data-import-all]').onclick=()=>{if(marked.size)marked.clear();else contacts.forEach((_,i)=>marked.add(i));draw();};el.querySelector('[data-import-more]').onclick=()=>{limit+=200;draw();};
    el.oninput=e=>{const {importName,importPhone}=e.target.dataset;if(importName!==undefined||importPhone!==undefined){const i=Number(importName??importPhone);contacts[i][importName!==undefined?'name':'phone']=e.target.value;marked.add(i);summarize();const row=e.target.closest('[data-import-row]');row.querySelector('[data-import-select]').checked=marked.has(i);row.querySelector('span').textContent=known.has(phoneKey(contacts[i].phone))?'Ya existe':valid(contacts[i])?'Listo':'Revisar nombre / teléfono';}};
    el.onchange=e=>{if(e.target.dataset.importSelect!==undefined){const i=Number(e.target.dataset.importSelect);e.target.checked?marked.add(i):marked.delete(i);summarize();e.target.checked=marked.has(i);}};
    el.querySelector('[data-import-save]').onclick=async()=>{if(busy||!marked.size)return;busy=true;const chosen=[...marked].map(i=>contacts[i]),allInputs=[...el.querySelectorAll('input,button')];allInputs.forEach(x=>x.disabled=true);let added=0,skipped=0,done=0;try{for(let i=0;i<chosen.length;i+=200){status.textContent='Importando '+Math.min(i+200,chosen.length)+' de '+chosen.length+'…';const result=await ctx.api('/api/admin/clients/import',{method:'POST',body:JSON.stringify({items:chosen.slice(i,i+200)})});added+=result.added;skipped+=result.skipped;done=i+Math.min(200,chosen.length-i);}await render();el.close();ctx.toast(added+' contactos agregados'+(skipped?' · '+skipped+' ya existentes':''),'success');}catch(error){status.textContent=error.message+(done?' Se procesaron '+done+' contactos. Podés volver a importar; los existentes no se duplican.':'');}finally{busy=false;allInputs.forEach(x=>x.disabled=false);el.querySelector('[data-import-save]').disabled=!marked.size;}};
    el.showModal();
  }
  let bound=false;
  function init(context){ctx=context;if(!bound){bound=true;document.addEventListener('input',e=>{if(e.target.matches('[data-client-filter]')){filters[e.target.dataset.clientFilter]=e.target.value;rows();}});document.addEventListener('change',e=>{if(e.target.matches('[data-client-select]')){const id=Number(e.target.dataset.clientSelect);e.target.checked?selected.add(id):selected.delete(id);rows();}});document.addEventListener('click',async e=>{try{if(e.target.closest('[data-client-import]'))await importContacts();if(e.target.closest('[data-client-new]'))await edit();if(e.target.closest('[data-client-edit]'))await edit(items.find(c=>c.id===Number(e.target.closest('[data-client-edit]').dataset.clientEdit)));if(e.target.closest('[data-client-select-all]')){const list=visible(),all=list.length&&list.every(c=>selected.has(c.id));list.forEach(c=>all?selected.delete(c.id):selected.add(c.id));rows();}if(e.target.closest('[data-client-offer]'))await offer();const order=e.target.closest('[data-client-order]');if(order){order.closest('dialog').close();await ctx.navigate(order.dataset.clientOrder==='custom'?'customOrders':'orders');}}catch(err){ctx.toast(err.message,'error');}});}return {render,edit,choose,linkDesign:(id,designId)=>ctx.api('/api/admin/clients/'+id+'/designs',{method:'POST',body:JSON.stringify({designId})})};}
  window.SalmosClients={init};
})();
